src-conf   := util/kconfig/conf.c \
              util/kconfig/zconf.tab.c

src-mconf  := util/kconfig/mconf.c \
              util/kconfig/zconf.tab.c \
              util/kconfig/lxdialog/checklist.c \
              util/kconfig/lxdialog/menubox.c \
              util/kconfig/lxdialog/util.c \
              util/kconfig/lxdialog/inputbox.c \
              util/kconfig/lxdialog/textbox.c \
              util/kconfig/lxdialog/yesno.c
